### ISSUE TITLE
Whitespace error on Jmeter 3.3 output

### ISSUE THREAD

**Issue by thejeff77** [tguzik/m2u#10]
Error: 

Exception in thread "main" com.thoughtworks.xstream.io.StreamException:  : only whitespace content allowed before start tag and not t (position: START_DOCUMENT seen t... @1:1) 
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:124)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:141)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.move(AbstractPullReader.java:118)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.moveDown(AbstractPullReader.java:103)
	at com.thoughtworks.xstream.io.xml.XppReader.<init>(XppReader.java:63)
	at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:54)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1040)
	at com.tguzik.util.xstream.AbstractXStreamConverter.fromXML(AbstractXStreamConverter.java:22)
	at com.tguzik.m2u.application.Main.run(Main.java:27)
	at com.tguzik.m2u.application.Main.main(Main.java:20)
Caused by: org.xmlpull.v1.XmlPullParserException: only whitespace content allowed before start tag and not t (position: START_DOCUMENT seen t... @1:1) 
	at org.xmlpull.mxp1.MXParser.parseProlog(MXParser.java:1519)
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1395)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:109)
	... 10 more

JTL file Results: rename result.txt to result.jtl

[result.txt](https://github.com/tguzik/m2u/files/1412616/result.txt)

**Comment by Masoma-Begum** [comment]
![yaml open in jmeter](https://user-images.githubusercontent.com/37552388/69265642-ca775c80-0bf3-11ea-8db2-6d6d419a31c9.JPG)
