### ISSUE TITLE
java.lang.NullPointerException while attempting execute

### ISSUE THREAD

**Issue by dsiiatski** [tguzik/m2u#5]
tguzik, thank you very much for taking the time to create this utility!

I am however having a little trouble getting it to work and was hoping maybe you can lend a hand, I get the feeling I missing something.

When I attempt convert a sample JTL file, I get a NullPointerException and I am not sure where to even start troubleshooting this, perhaps you or someone has encountered this before.

The error is below:
xception in thread "main" java.lang.NullPointerException
	at com.tguzik.m2u.data.JtlToJunitConverter.convertSample(JtlToJunitConverter.java:53)
	at com.tguzik.m2u.data.JtlToJunitConverter.convertHttpSample(JtlToJunitConverter.java:86)
	at com.tguzik.m2u.data.JtlToJunitConverter.apply(JtlToJunitConverter.java:38)
	at com.tguzik.m2u.application.Main.process(Main.java:34)
	at com.tguzik.m2u.application.Main.main(Main.java:19)

I have also attached the build log and the sample JTL file I am trying to convert.

Any help would be greatly appreciated as this utility will be infinitely useful!
[m2u_buildlog.log.txt](https://github.com/tguzik/m2u/files/917485/m2u_buildlog.log.txt)
[results.xml.txt](https://github.com/tguzik/m2u/files/917486/results.xml.txt)

**Comment by dsiiatski** [comment]
I was correct about this being my mistake -- I was not saving ElapsedTime and TimeStamp in my input file -- after including that information everything works -- thank you tguzik!
